### PR TITLE
Added ViewRecentRoomHistory + tests

### PR DESCRIPTION
**Pull request by frankneumann**
1.Added ViewRecentRoomHistory + tests
2. Made test code more reliable

### CODE REVIEW

**Comment by KyleGobel** [comment]
I didn't see this till just now..my bad.

I changed the test a bit just to create a new room (unique name) everytime just so I could get this republished to nuget.  Which obv caused a conflict with your updated test code

**Comment by frankneumann** [comment]
OK - bad luck.


Can you do the merge or will I have to modify the code in my fork?


Frank






Von: notifications@github.com
Gesendet: ‎Freitag‎, ‎30‎. ‎Januar‎ ‎2015 ‎04‎:‎25
An: KyleGobel/Hipchat-CS
Cc: Frank Neumann





I didn't see this till just now..my bad.

I changed the test a bit just to create a new room (unique name) everytime just so I could get this republished to nuget. Which obv caused a conflict with your updated test code

**Comment by KyleGobel** [comment]
I merged it :).  Thanks Frank

**Comment by frankneumann** [comment]
Thanks. Are you going to create a new version for Nuget as well?

I would like to notify my students to use the new version.

 

Best regards,

 

Frank

 

Gesendet: Freitag, 30. Januar 2015 um 14:23 Uhr
Von: "Kyle Gobel" <notifications@github.com>
An: KyleGobel/Hipchat-CS <Hipchat-CS@noreply.github.com>
Cc: frankneumann <frank.neumann.karlshorst@web.de>
Betreff: Re: [Hipchat-CS] Added ViewRecentRoomHistory + tests (#19)


I merged it :). Thanks Frank

**Comment by KyleGobel** [comment]
yup new version is pushed.

We'll have to figure out something soon about the tests, might just have to disable all of them for the build server.  If i test it locally, and then try to run a build on myget I get rate limited exceptions...have to wait out the cooldown and rebuild

**Pull request merged**
